cutoff_len: 1024
dataset: webnovel
dataset_dir: data
do_train: true
finetuning_type: lora
flash_attn: auto
fp16: false
gradient_accumulation_steps: 8
learning_rate: 5.0e-05
logging_steps: 5
lora_alpha: 16
lora_dropout: 0
lora_rank: 8
lora_target: query_key_value
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 100000
model_name_or_path: bigscience/bloom-560m
num_train_epochs: 3.0
optim: adamw_torch
output_dir: saves/BLOOM-560M/lora/train_2024-05-18-17-27-14
packing: false
per_device_train_batch_size: 2
plot_loss: true
preprocessing_num_workers: 16
report_to: none
save_steps: 100
stage: sft
template: default
warmup_steps: 0
